### ISSUE TITLE
Ad still showing: Leo dictionary

### ISSUE THREAD

**Issue by tonyp** [chiehmin/MinMinGuard#58]
The "Leo dictionary" app stll shows an ad at the bottom of the main page.

https://play.google.com/store/apps/details?id=org.leo.android.dict&hl=en

**Comment by chiehmin** [comment]
Just modified url filtering method and add url filtering option back. should be removed by enabling url filtering.

**Comment by tonyp** [comment]
I can confirm the ad gets blocked with the new 2.0.7, thank you.
But the ad space doesn't get freed, it now works pretty much like "conventional" hosts ad blockers.

**Comment by chiehmin** [comment]
I will look into it.

**Comment by chiehmin** [comment]
Should be fixed by this d181d144817c4bc33c712c6b0c7db36f4027c289

**Comment by chiehmin** [comment]
Please update to alpha8. Adview should be removed :)

**Comment by tonyp** [comment]
Works like a charm, thank you!

**Comment by aphirst** [comment]
I'm using Leo 6.5.1 with MinMinGuard 2.0 beta5, and I'm getting ads at the bottom of most pages, including the "Search" pages. I have also tried enabling URL Filtering for this app in the MMG settings, but the issue persists. I guess they updated/changed their ad network / implementation?
